[tool.poetry]
name = "502-page-using-bottle"
version = "0.1.0"
description = ""
authors = ["NineCloud"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
bottle = "^0.12.25"
tailwindcss = "^0.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
